# Generated by Django 5.0.2 on 2024-02-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=50, null=True)),
                ("source_name", models.CharField(blank=True, max_length=50, null=True)),
                ("author", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, null=True)),
                ("published_at", models.DateTimeField()),
                ("content", models.TextField(max_length=1000)),
            ],
        ),
    ]
